import "./index.css";
import Navbar from "./Navbar";
import Home from "./Home"; 


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function App() {
  return (

      <>
        <Navbar />
        <Home />
      </>

  );
}
